# Generated by Django 2.2.5 on 2020-03-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20200212_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-title'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
